print(pi)
print(2*2)
print("Area of the unit circle is: ", pi*2**2)
print("Area of the unit circle is: ");(pi*2**2)
cat("Area of the unit circle is: ", pi*2**2)
cat("Area of the unit circle is: ", pi*2**2,"\n")
cat("Circumference is: ", 2*pi*2)
